<a href="https://colab.research.google.com/github/TinNguyenday/TH-toancaocap/blob/main/TH5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TH1


In [1]:

x= 3 
print (x)

3


In [2]:
import math
x = math.sqrt(1+x)
print (x)

2.0


TH2


In [3]:
x = 3
lap = 1 
while (x!= math.sqrt (x+ 1)):
  x = math.sqrt(x +1 )
  lap + lap + 1

In [4]:
print(x)

1.618033988749895


In [6]:
print(lap)

1


TH3


In [7]:
  from sympy.core.singleton import S
import sympy as sp 
from sympy import Symbol
x = Symbol('x')
sp.solve(x-sp.sqrt(1+x),x)

[1/2 + sqrt(5)/2]

TH4

In [8]:
import numpy as np
v1 = np.array([1.,2.,3.]) # tạo vecto 3 chiều
v2 = np.array ([2.,1.,0.])
# cộng vecto
v3 = v1 + v2 
print (v3)

[3. 3. 3.]


thực hiện phép toán các vecto

In [9]:
3*v1 + 2*v2

array([7., 8., 9.])

In [10]:
[1,2,3]+[2,1,0]


[1, 2, 3, 2, 1, 0]

In [11]:
3*[1,2,3]+2*[2,1,0]


[1, 2, 3, 1, 2, 3, 1, 2, 3, 2, 1, 0, 2, 1, 0]

ghép nối các vecto

In [12]:
v4 = np.hstack([v1, v2 ])
v4

array([1., 2., 3., 2., 1., 0.])

nhân vô hướng 2 vecto

In [13]:
np.dot(v1,v2)


4.0

tính sin của vecto

In [14]:
angles = np.linspace(0, np.pi/2, 3 )
angles

array([0.        , 0.78539816, 1.57079633])

In [15]:
np.sin(angles)


array([0.        , 0.70710678, 1.        ])